name       : trousers
version    : 0.3.14
release    : 1
source     :
    - https://sourceforge.net/projects/trousers/files/trousers/0.3.14/trousers-0.3.14.tar.gz : ce50713a261d14b735ec9ccd97609f0ad5ce69540af560e8c3ce9eb5f2d28f47
license    : CPL-1.0
component  : programming.library
summary    : The open-source TCG Software Stack
description: |
    The open-source TCG Software Stack
builddeps  :
    - pkgconfig(openssl)
    - pkgconfig(systemd)
setup      : |
    %configure --with-gui-openssl
build      : |
    %make
install    : |
    %make_install
    # remove static libraries
    find $installdir -type f -name "*.a" -delete
    # setup systemd service, sysusers.d and tmpfiles.d 
    install -Dm00644 $pkgfiles/tcsd.service $installdir/%libdir%/systemd/system/tcsd.service
    install -Dm00644 $pkgfiles/trousers.sysusers $installdir/%libdir%/sysusers.d/trousers.conf
    install -Dm00644 $pkgfiles/trousers.tmpfiles $installdir/%libdir%/tmpfiles.d/trousers.conf
